import type { EnterpriseGuide } from './enterprise-center-data';

const sections=(context:string[],workflow:string[],assurance:string[])=>[
  {heading:'Context and preparation',items:context},
  {heading:'Guided coaching workflow',items:workflow},
  {heading:'Validation and responsible use',items:assurance},
];

export const aiCoachGuides:EnterpriseGuide[]=[
  {slug:'learning-coach',title:'AI Learning Coach',summary:'Create a role-aligned study plan using current capability, target outcomes and available time.',objective:'Produce a practical learning sequence with measurable evidence and regular review points.',sections:sections(['Define the target role and learning outcome','Record current knowledge, constraints and preferred learning style','Select authoritative references and practical exercises'],['Break the goal into weekly milestones','Combine reading, labs, recall and review','Adjust the plan using completed evidence and feedback'],['Verify technical claims against trusted documentation','Protect personal and organisational information','Retain learner ownership of final decisions'])},
  {slug:'interview-coach',title:'AI Interview Coach',summary:'Prepare structured technical and behavioural interview practice for a target role.',objective:'Improve answer quality, technical depth and communication under realistic questioning.',sections:sections(['Analyse the role description and competency areas','Identify likely technical, scenario and behavioural questions','Prepare concise evidence from real experience'],['Run timed mock interviews','Challenge assumptions and request deeper reasoning','Improve answers using STAR and architecture trade-off structures'],['Do not invent experience or qualifications','Validate technical recommendations','Record gaps for further study'])},
  {slug:'resume-reviewer',title:'AI Resume Reviewer',summary:'Review a resume against a target role while preserving factual accuracy and clear evidence.',objective:'Create a focused, credible and ATS-compatible resume improvement plan.',sections:sections(['Extract mandatory and desirable role requirements','Map verified experience and achievements','Identify unsupported or ambiguous statements'],['Improve role alignment and evidence language','Prioritise measurable outcomes and relevant technologies','Remove repetition and low-value content'],['Never fabricate experience, employers or certifications','Protect personal data','Complete a final human review'])},
  {slug:'career-advisor',title:'AI Career Advisor',summary:'Assess role options, capability gaps and realistic next steps across cloud and infrastructure careers.',objective:'Create an evidence-based career roadmap with clear priorities and decision points.',sections:sections(['Define preferred roles, location and employment constraints','Assess transferable experience and marketable strengths','Identify capability and evidence gaps'],['Compare role pathways and required investment','Create a 30, 60 and 90-day action plan','Track applications, learning and feedback'],['Separate facts from assumptions','Validate current market information before decisions','Keep financial and visa decisions under qualified review'])},
  {slug:'architecture-reviewer',title:'AI Architecture Reviewer',summary:'Challenge proposed designs across requirements, security, resilience, cost and operability.',objective:'Improve architecture quality through structured questions and documented trade-offs.',sections:sections(['Provide business requirements, constraints and assumptions','Describe components, data flows and dependencies','Identify applicable standards and risk appetite'],['Review alternatives and failure modes','Test identity, network, recovery and operational controls','Capture decisions and unresolved risks'],['Validate recommendations with platform documentation','Require accountable human approval','Do not expose confidential architecture data'])},
  {slug:'cost-advisor',title:'AI Cloud Cost Advisor',summary:'Review cloud consumption, design choices and operating practices for optimisation opportunities.',objective:'Identify safe cost improvements without compromising reliability, security or compliance.',sections:sections(['Define workload purpose, demand and service objectives','Collect current usage, commitments and cost allocation','Identify lifecycle and contractual constraints'],['Assess rightsizing, scheduling, storage and commitment options','Compare cost against performance and resilience','Prioritise actions by value, risk and effort'],['Verify prices and commercial terms using current sources','Require change control before implementation','Track realised savings rather than estimates alone'])},
  {slug:'troubleshooting-coach',title:'AI Troubleshooting Coach',summary:'Guide evidence-driven diagnosis while avoiding unsupported changes and premature conclusions.',objective:'Create a safe troubleshooting path that preserves service stability and learning.',sections:sections(['Define symptoms, scope, timeline and recent changes','Collect logs, metrics, configuration and dependency evidence','Establish safety boundaries and rollback options'],['Form and rank testable hypotheses','Run low-risk diagnostic steps first','Record outcomes and update the working theory'],['Do not execute destructive actions without approval','Validate commands and platform applicability','Escalate when evidence or authority is insufficient'])},
  {slug:'study-planner',title:'AI Study Planner',summary:'Convert broad certification or capability goals into a sustainable personal schedule.',objective:'Build a realistic plan balancing learning, practice, revision and assessment.',sections:sections(['Select the target outcome and deadline','Estimate available weekly time','Identify prerequisite knowledge and resources'],['Schedule focused topics, labs and spaced review','Include checkpoints and recovery time','Adapt the plan using progress data'],['Use official exam and product sources','Avoid unsafe credential sharing','Treat generated schedules as adjustable guidance'])},
];
