import type { EnterpriseGuide } from './enterprise-center-data';

const sections=(plan:string[],delivery:string[],evidence:string[])=>[
  {heading:'Plan and design',items:plan},
  {heading:'Build and validate',items:delivery},
  {heading:'Evidence and review',items:evidence},
];

export const architectureStudioGuides:EnterpriseGuide[]=[
  {slug:'cloud-topology-studio',title:'Cloud Topology Studio',summary:'Model subscriptions, networks, workloads, controls and operational dependencies before implementation.',objective:'Create a reviewable cloud topology with explicit boundaries, dependencies and ownership.',sections:sections(['Define business capabilities and workload boundaries','Identify subscriptions, accounts, regions and environments','Map identity, network and management planes'],['Draft context, container and deployment views','Annotate traffic paths, controls and failure domains','Review assumptions with security and operations'],['Publish architecture decision records','Capture unresolved risks and owners','Version the approved topology with delivery evidence'])},
  {slug:'landing-zone-explorer',title:'Landing Zone Explorer',summary:'Design a governed platform foundation covering identity, connectivity, policy, logging and workload onboarding.',objective:'Produce a landing-zone blueprint that teams can implement and operate consistently.',sections:sections(['Define tenant and management hierarchy','Set platform and workload responsibilities','Select policy, logging and connectivity baselines'],['Model onboarding and exception workflows','Validate isolation, routing and shared services','Test scale, recovery and operational ownership'],['Create the control matrix','Record approved exceptions','Publish onboarding and handover guidance'])},
  {slug:'network-flow-designer',title:'Network Flow Designer',summary:'Trace ingress, east-west, egress and administrative traffic through security and availability controls.',objective:'Create precise network-flow documentation suitable for design and change review.',sections:sections(['Inventory sources, destinations, protocols and ports','Classify trust zones and data sensitivity','Identify DNS, proxy, firewall and load-balancing dependencies'],['Draw normal and failure-state flows','Validate asymmetric routing and name resolution','Test observability and troubleshooting points'],['Create firewall-rule evidence','Record flow owners and review dates','Publish an operational troubleshooting map'])},
  {slug:'security-boundary-model',title:'Security Boundary Model',summary:'Visualise identity, network, workload and data boundaries with their enforcement points.',objective:'Make trust assumptions and security controls visible and testable.',sections:sections(['Identify identities, assets and trust transitions','Classify privileged and non-privileged paths','Map preventive, detective and recovery controls'],['Model attack paths and compensating controls','Validate secrets, keys and certificate handling','Review least privilege and separation of duties'],['Document residual risk','Link controls to evidence','Schedule control-owner reviews'])},
  {slug:'resilience-simulator',title:'Resilience Simulator',summary:'Walk through component, zone, region and dependency failures before production release.',objective:'Demonstrate that architecture recovery objectives are realistic and operationally executable.',sections:sections(['Define critical journeys and recovery objectives','Identify single points of failure','Prioritise dependency and capacity risks'],['Simulate component and regional outages','Validate degraded-mode behaviour','Exercise restoration and data-consistency steps'],['Capture recovery timings','Record corrective actions and owners','Publish the resilience acceptance decision'])},
];

export const templateLibraryGuides:EnterpriseGuide[]=[
  {slug:'terraform-module-pack',title:'Terraform Module Pack',summary:'Structure reusable infrastructure modules with secure defaults, versioning and tests.',objective:'Deliver maintainable Terraform modules that teams can consume safely.',sections:sections(['Define module boundaries and contracts','Select inputs, outputs and validation rules','Document providers, versions and state assumptions'],['Add examples, linting and policy checks','Test idempotency and upgrade paths','Publish semantic versions and changelogs'],['Provide usage evidence','Record known limitations','Define module ownership and support'])},
  {slug:'bicep-arm-pack',title:'Bicep and ARM Pack',summary:'Create governed Azure deployment templates with modular composition and environment parameters.',objective:'Provide repeatable Azure templates with clear controls and deployment evidence.',sections:sections(['Model resources and dependency order','Separate platform and workload concerns','Define parameter and secret handling'],['Run validation and what-if checks','Test environment-specific configurations','Add policy and diagnostic settings'],['Publish deployment examples','Capture rollback guidance','Record template ownership'])},
  {slug:'pipeline-template-pack',title:'Pipeline Template Pack',summary:'Standardise build, test, security, approval and deployment stages across delivery teams.',objective:'Create reusable pipelines that improve speed without weakening governance.',sections:sections(['Define triggers, environments and approvals','Select artifact and versioning conventions','Map secrets and identity requirements'],['Add quality and security gates','Implement deployment and rollback jobs','Test concurrency and failure handling'],['Publish adoption guidance','Measure lead time and failure rate','Maintain versioned release notes'])},
  {slug:'container-platform-pack',title:'Container Platform Pack',summary:'Package Docker, Kubernetes and Helm examples with security and operational baselines.',objective:'Provide safe starter assets for containerised workloads.',sections:sections(['Define image and runtime standards','Model resource, network and storage requirements','Select health, scaling and disruption controls'],['Build and scan images','Validate manifests and chart values','Test rollout, rollback and failure behaviour'],['Publish runbooks and examples','Record supported versions','Assign platform support ownership'])},
  {slug:'observability-template-pack',title:'Observability Template Pack',summary:'Standardise metrics, logs, traces, dashboards, alerts and service-level objectives.',objective:'Ensure every delivered service includes actionable production observability.',sections:sections(['Define service objectives and critical signals','Select telemetry sources and retention','Map alert ownership and escalation'],['Create dashboards and alert rules','Test signal quality and failure detection','Validate cost and access controls'],['Publish dashboard links and runbooks','Capture alert-test evidence','Review noise and coverage regularly'])},
];

export const interviewSimulatorGuides:EnterpriseGuide[]=[
  {slug:'cloud-architect-simulation',title:'Cloud Architect Simulation',summary:'Practise requirements discovery, trade-off analysis and architecture defence.',objective:'Demonstrate structured cloud architecture reasoning under interview conditions.',sections:sections(['Clarify business and non-functional requirements','State assumptions and constraints','Prioritise security, resilience, cost and operability'],['Present a target architecture','Explain alternatives and trade-offs','Respond to failure and scale challenges'],['Summarise decisions concisely','Record gaps for further study','Score clarity, depth and evidence'])},
  {slug:'devops-platform-simulation',title:'DevOps and Platform Simulation',summary:'Practise pipeline, platform, developer-experience and reliability scenarios.',objective:'Show practical platform-engineering judgement and delivery leadership.',sections:sections(['Define users and platform outcomes','Identify bottlenecks and control requirements','Select measurable success criteria'],['Design paved roads and self-service workflows','Explain pipeline and environment controls','Handle deployment and adoption failures'],['Capture improvement actions','Score operational realism','Build portfolio evidence from the response'])},
  {slug:'wintel-infrastructure-simulation',title:'Wintel Infrastructure Simulation',summary:'Practise Windows, Hyper-V, identity, patching, clustering and production-support scenarios.',objective:'Demonstrate senior infrastructure troubleshooting and design capability.',sections:sections(['Establish scope, symptoms and business impact','Identify dependencies and recent changes','Define safe diagnostic boundaries'],['Explain diagnosis and recovery sequence','Address security, backup and rollback','Communicate decisions to stakeholders'],['Document evidence and lessons','Score risk management','Create follow-up prevention actions'])},
  {slug:'behavioural-leadership-simulation',title:'Behavioural and Leadership Simulation',summary:'Prepare structured examples for ownership, conflict, risk, influence and delivery leadership.',objective:'Communicate leadership evidence clearly using concise, outcome-focused examples.',sections:sections(['Select relevant situations and stakeholders','Define personal responsibility','Quantify risk, complexity and constraints'],['Explain actions and judgement','Show communication and escalation','Describe measurable outcomes'],['Capture lessons and improvements','Remove unnecessary detail','Score ownership and executive clarity'])},
  {slug:'incident-command-simulation',title:'Incident Command Simulation',summary:'Practise technical leadership during a high-impact production incident.',objective:'Demonstrate calm prioritisation, communication and evidence-based recovery.',sections:sections(['Confirm severity, scope and command roles','Protect safety and service integrity','Establish communication cadence'],['Drive diagnosis and mitigations','Track decisions, risks and owners','Plan recovery validation and rollback'],['Prepare stakeholder summary','Define post-incident actions','Score command discipline and clarity'])},
];

export const documentationGuides:EnterpriseGuide[]=[
  {slug:'architecture-rfc',title:'Architecture RFC',summary:'Document context, options, decisions, risks and implementation consequences.',objective:'Produce an RFC that enables informed technical and governance approval.',sections:sections(['Define problem, scope and stakeholders','Capture constraints and success criteria','Compare viable options'],['Document the recommended design','Describe security, cost and operational impacts','Set decision and review checkpoints'],['Record approval and dissent','Link supporting evidence','Maintain decision status and supersession'])},
  {slug:'standard-operating-procedure',title:'Standard Operating Procedure',summary:'Create repeatable operational procedures with prerequisites, controls and validation.',objective:'Enable authorised engineers to execute routine work safely and consistently.',sections:sections(['Define trigger, scope and permissions','List prerequisites and dependencies','Set change, backup and rollback requirements'],['Write precise ordered steps','Add validation and stop conditions','Include escalation and evidence capture'],['Test with an independent operator','Record revision history','Assign document ownership'])},
  {slug:'disaster-recovery-runbook',title:'Disaster Recovery Runbook',summary:'Document activation, recovery, validation and return-to-service procedures.',objective:'Provide an executable recovery plan aligned with approved recovery objectives.',sections:sections(['Define invocation criteria and authority','Map services, dependencies and recovery order','Confirm recovery objectives and data sources'],['Document restoration and validation','Include communications and decision points','Test alternate-site and degraded scenarios'],['Capture exercise evidence','Track recovery gaps','Review after architecture or supplier changes'])},
  {slug:'business-continuity-plan',title:'Business Continuity Plan',summary:'Describe how critical services continue through technology, people or supplier disruption.',objective:'Connect technical resilience with business priorities and manual workarounds.',sections:sections(['Identify critical activities and tolerances','Map people, sites, suppliers and technology','Define continuity strategies'],['Document activation and communications','Exercise realistic disruption scenarios','Validate workarounds and capacity'],['Record findings and actions','Maintain contact and dependency data','Obtain business-owner approval'])},
  {slug:'production-handover-pack',title:'Production Handover Pack',summary:'Assemble the evidence required for safe operational acceptance of a new or changed service.',objective:'Transfer a supportable service with clear ownership, controls and known risks.',sections:sections(['Confirm scope, service owners and support model','Collect architecture, security and test evidence','Document dependencies, licences and suppliers'],['Provide monitoring, backup and recovery details','Complete runbooks, access and escalation paths','Review open risks and exceptions'],['Obtain operational acceptance','Archive release evidence','Schedule post-release review'])},
];
