import type { EnterpriseGuide } from './enterprise-center-data';

const labSections=(prepare:string[],execute:string[],validate:string[])=>[
  {heading:'Objectives and preparation',items:prepare},
  {heading:'Guided implementation',items:execute},
  {heading:'Validation, troubleshooting and cleanup',items:validate},
];

export const interactiveLabGuides:EnterpriseGuide[]=[
  {slug:'azure-virtual-machine',title:'Azure Virtual Machine Lab',summary:'Deploy and validate a secure Azure virtual machine with controlled network access and operational monitoring.',objective:'Build a repeatable VM deployment while documenting security, connectivity, monitoring and cleanup evidence.',sections:labSections(['Confirm subscription, region, naming and resource-group standards','Define identity, network, image, size and disk requirements','Prepare rollback, cost and access controls'],['Create the resource group, network path and virtual machine','Apply least-privilege access and secure management settings','Enable monitoring and capture deployment evidence'],['Validate connectivity, identity, patching and telemetry','Investigate failed provisioning or access safely','Remove lab resources and confirm cost cleanup'])},
  {slug:'azure-networking',title:'Azure Networking Lab',summary:'Build a segmented virtual network with subnets, routing, security controls and tested connectivity.',objective:'Demonstrate secure network design, traffic flow validation and evidence-driven troubleshooting.',sections:labSections(['Define address spaces, subnet roles and connectivity requirements','Identify DNS, routing, firewall and private-access dependencies','Document expected traffic flows before implementation'],['Create the virtual network and subnets','Apply network security and routing controls','Deploy test endpoints and collect effective configuration'],['Test permitted and denied flows','Trace DNS, route and security-rule issues','Delete temporary endpoints and unused resources'])},
  {slug:'terraform-foundations',title:'Terraform Foundations Lab',summary:'Create a maintainable Terraform workflow covering configuration, state, planning, deployment and teardown.',objective:'Produce safe infrastructure-as-code with predictable review and lifecycle controls.',sections:labSections(['Install and verify the approved Terraform version','Define provider authentication and remote-state expectations','Create naming, tagging and repository standards'],['Write formatted configuration using variables and outputs','Run init, validate and plan before deployment','Apply the reviewed plan and record resulting resources'],['Compare deployed state with intended configuration','Diagnose provider, state and dependency failures','Destroy lab resources and protect retained state evidence'])},
  {slug:'aks-foundations',title:'AKS Foundations Lab',summary:'Deploy and operate a foundational Azure Kubernetes Service environment with secure access and workload validation.',objective:'Understand AKS dependencies, cluster access, workload deployment, observability and safe cleanup.',sections:labSections(['Confirm subscription quotas, identity and network design','Prepare kubectl, Azure CLI and approved versions','Define cluster, node-pool and workload requirements'],['Deploy the cluster and configure controlled access','Publish a test workload and service','Inspect nodes, pods, events, logs and resource health'],['Validate workload availability and scaling behaviour','Troubleshoot scheduling, image and connectivity issues','Remove workloads and delete the lab cluster safely'])},
  {slug:'github-actions-pipeline',title:'GitHub Actions Pipeline Lab',summary:'Build a controlled CI pipeline with validation, artifact handling and protected deployment behaviour.',objective:'Create a traceable workflow that fails safely and provides useful evidence for reviewers.',sections:labSections(['Define triggers, permissions, environments and required secrets','Identify lint, test, build and deployment quality gates','Prepare a small application or infrastructure example'],['Create the workflow with pinned or trusted actions','Add dependency installation, validation and build jobs','Publish useful summaries or artifacts without exposing secrets'],['Test successful and failed execution paths','Review permissions, logs, caching and concurrency','Remove temporary credentials and document rollback'])},
  {slug:'azure-policy',title:'Azure Policy Lab',summary:'Author, assign and test Azure Policy controls using a safe non-production scope.',objective:'Demonstrate policy evaluation, remediation planning, exemptions and governance evidence.',sections:labSections(['Select a measurable governance requirement','Review built-in definitions before creating custom policy','Choose safe assignment scope and enforcement mode'],['Create or select the policy definition','Assign it with parameters and clear ownership metadata','Deploy compliant and non-compliant test resources'],['Review compliance results and evaluation timing','Test remediation or exemption processes under approval','Remove assignments and temporary resources'])},
  {slug:'entra-identity',title:'Entra Identity Lab',summary:'Practise identity, group, role and access-review controls without weakening tenant security.',objective:'Apply least privilege and produce auditable identity-governance evidence.',sections:labSections(['Use approved test identities and a non-production scope','Define role, group and access lifecycle requirements','Record break-glass and recovery boundaries'],['Create controlled groups and role assignments','Apply time-bound or reviewable access where available','Capture sign-in, audit and assignment evidence'],['Validate effective access and denied actions','Investigate propagation or permission issues','Remove test access and confirm revocation'])},
  {slug:'powershell-automation',title:'PowerShell Automation Lab',summary:'Develop a safe PowerShell automation script with validation, logging and reversible execution.',objective:'Create production-minded automation that handles input, errors, evidence and rollback clearly.',sections:labSections(['Define the task, supported systems and safety boundaries','Use approved modules and minimum required privileges','Prepare test data and expected outcomes'],['Implement parameter validation and WhatIf support where applicable','Add structured error handling and useful logging','Run against limited test scope before wider execution'],['Verify idempotence and expected state','Review errors without suppressing evidence','Revert test changes and retain the execution record'])},
];