export type OperationsGuide = { slug:string; title:string; summary:string; sections:{title:string; items:string[]}[] };

export const operationsGuides: OperationsGuide[] = [
  {slug:'production-readiness',title:'Production Readiness Review',summary:'Validate ownership, supportability, security, resilience and safe release controls before go-live.',sections:[{title:'Service ownership',items:['Named business and technical owners','Support model, escalation path and rota','Runbooks linked to known failure modes']},{title:'Release controls',items:['Automated quality gates','Rollback tested with time objective','Environment configuration verified']},{title:'Operational acceptance',items:['Monitoring and alerting active','Capacity and cost reviewed','Known risks explicitly accepted']}]},
  {slug:'security-baseline',title:'Security Baseline',summary:'Apply minimum identity, network, data, supply-chain and audit controls before production use.',sections:[{title:'Identity',items:['Least privilege and no shared accounts','Privileged access is time-bound','Workload identities replace embedded secrets']},{title:'Platform controls',items:['Encryption in transit and at rest','Network exposure is intentional','Dependencies and images are scanned']},{title:'Evidence',items:['Audit logs retained','Exceptions have expiry dates','Security ownership is documented']}]},
  {slug:'observability-plan',title:'Observability Plan',summary:'Define the signals, dashboards, alerts and diagnostic evidence required to operate confidently.',sections:[{title:'Signals',items:['Golden signals or equivalent service indicators','Structured logs with correlation IDs','Distributed traces for critical paths']},{title:'Alert quality',items:['Alerts map to user impact','Actionable thresholds and runbooks','Noise and duplicate alerts reviewed']},{title:'Operational views',items:['Service health dashboard','Deployment and dependency overlays','Capacity and saturation trends']}]},
  {slug:'disaster-recovery',title:'Disaster Recovery Plan',summary:'Translate business recovery needs into tested technical recovery procedures and evidence.',sections:[{title:'Objectives',items:['RTO and RPO agreed with the business','Critical dependencies identified','Data consistency expectations defined']},{title:'Recovery design',items:['Backups isolated and restorable','Failover sequence documented','Access during emergency is controlled']},{title:'Validation',items:['Restore tests scheduled','Exercise results recorded','Gaps tracked to closure']}]},
  {slug:'incident-response',title:'Incident Response Playbook',summary:'Provide a disciplined sequence for detection, containment, recovery and learning.',sections:[{title:'Initial response',items:['Declare severity and incident lead','Stabilise before deep investigation','Preserve timestamps and evidence']},{title:'Communication',items:['Regular stakeholder updates','Single source of truth','Clear customer impact statement']},{title:'Closure',items:['Root cause distinguishes trigger and systemic cause','Actions have owners and deadlines','Learning is shared without blame']}]},
  {slug:'service-level-objectives',title:'Service Level Objectives',summary:'Use measurable reliability targets and error budgets to balance delivery speed and service health.',sections:[{title:'Define reliability',items:['Select user-centred SLIs','Set realistic SLO targets','Document measurement windows']},{title:'Use error budgets',items:['Track remaining budget','Adjust release risk when budget is low','Review chronic reliability debt']},{title:'Governance',items:['Publish ownership and reporting','Review breaches and trends','Avoid vanity availability numbers']}]},
];

export const operationsGuideMap = Object.fromEntries(operationsGuides.map((guide)=>[guide.slug,guide]));