import type { EnterpriseGuide } from './enterprise-center-data';

const sections=(prepare:string[],operate:string[],evidence:string[])=>[
  {heading:'Prepare and design',items:prepare},
  {heading:'Operate and improve',items:operate},
  {heading:'Evidence and governance',items:evidence},
];

export const observabilityGuides:EnterpriseGuide[]=[
  {slug:'telemetry-strategy',title:'Telemetry Strategy',summary:'Define the metrics, logs, traces and events required to understand service health.',objective:'Create an actionable telemetry model aligned to user journeys and operational risk.',sections:sections(['Identify critical services and user journeys','Define golden signals and diagnostic data','Set retention, access and cost boundaries'],['Instrument applications and infrastructure','Validate signal quality and correlation','Remove blind spots and duplicate telemetry'],['Publish ownership and data standards','Record coverage evidence','Review telemetry after major change'])},
  {slug:'dashboard-design',title:'Dashboard Design',summary:'Build role-based dashboards that communicate health, risk and trend clearly.',objective:'Provide concise operational views for engineers, service owners and leaders.',sections:sections(['Define dashboard audiences and decisions','Select meaningful indicators and thresholds','Design normal and degraded-state views'],['Build service and dependency panels','Test readability during incidents','Tune refresh rates and drill-down links'],['Record dashboard ownership','Review usage and gaps','Retire obsolete views'])},
  {slug:'alert-engineering',title:'Alert Engineering',summary:'Create actionable alerts with clear ownership, severity and response guidance.',objective:'Reduce noise while improving detection and response quality.',sections:sections(['Define symptoms requiring human action','Set severity and routing rules','Link alerts to service objectives'],['Test thresholds and deduplication','Add context and runbook links','Measure false positives and missed events'],['Publish alert ownership','Track tuning decisions','Review after incidents'])},
  {slug:'service-level-objectives',title:'Service-Level Objectives',summary:'Translate customer expectations into measurable indicators, objectives and error budgets.',objective:'Use service levels to balance reliability, delivery speed and investment.',sections:sections(['Identify critical user outcomes','Choose measurable service indicators','Set realistic objectives and review periods'],['Implement reporting and burn-rate alerts','Review breaches and contributing factors','Use error budgets in delivery decisions'],['Publish agreed objectives','Record exceptions and risks','Review with business owners'])},
  {slug:'observability-maturity',title:'Observability Maturity Review',summary:'Assess telemetry coverage, diagnostic capability and operational adoption.',objective:'Create a prioritised roadmap for improving observability maturity.',sections:sections(['Assess instrumentation and ownership','Review incident diagnostic evidence','Identify cost and access constraints'],['Score coverage and usability','Prioritise high-risk gaps','Implement measurable improvements'],['Publish maturity findings','Assign roadmap owners','Reassess on a fixed cadence'])},
];

export const disasterRecoveryGuides:EnterpriseGuide[]=[
  {slug:'recovery-strategy',title:'Recovery Strategy',summary:'Define recovery priorities, dependencies, objectives and restoration patterns.',objective:'Create an approved recovery strategy aligned to business impact.',sections:sections(['Identify critical services and data','Set RTO and RPO targets','Map dependencies and recovery order'],['Select backup, replication and failover patterns','Validate capacity and access','Plan communications and decision authority'],['Publish the strategy','Record residual risk','Review after architecture change'])},
  {slug:'backup-assurance',title:'Backup Assurance',summary:'Validate backup scope, protection controls, retention and recoverability.',objective:'Demonstrate that protected data can be restored securely and within target.',sections:sections(['Inventory systems and data classes','Define backup schedules and retention','Separate credentials and administrative paths'],['Monitor backup completion and integrity','Test representative restores','Resolve coverage and capacity gaps'],['Retain restore evidence','Report exceptions','Review supplier and platform changes'])},
  {slug:'failover-exercise',title:'Failover Exercise',summary:'Plan and execute controlled failover testing for infrastructure and services.',objective:'Prove that failover procedures work without unacceptable risk.',sections:sections(['Define scope and success criteria','Confirm roles, approvals and rollback','Prepare monitoring and communications'],['Execute failover and validation','Measure recovery timings','Restore normal operation safely'],['Document findings','Assign corrective actions','Update runbooks and architecture'])},
  {slug:'regional-recovery',title:'Regional Recovery',summary:'Prepare for loss of a site, region or major shared dependency.',objective:'Validate cross-region recovery under realistic constraints.',sections:sections(['Map regional dependencies and data flows','Confirm alternate-region capacity','Define DNS, identity and network changes'],['Exercise deployment and data restoration','Validate degraded service modes','Test supplier and communication paths'],['Capture actual recovery performance','Document unresolved risks','Obtain service-owner acceptance'])},
  {slug:'recovery-governance',title:'Recovery Governance',summary:'Establish ownership, testing cadence, evidence and risk oversight for recovery capability.',objective:'Keep recovery plans current, tested and accountable.',sections:sections(['Define policy and minimum standards','Assign service and recovery owners','Set exercise schedules and evidence rules'],['Track plan currency and test completion','Escalate material gaps','Integrate findings with change governance'],['Report recovery posture','Maintain action logs','Review annually with leadership'])},
];

export const complianceGuides:EnterpriseGuide[]=[
  {slug:'control-framework',title:'Control Framework',summary:'Map technical and operational controls to organisational and regulatory requirements.',objective:'Create a practical control model with accountable ownership.',sections:sections(['Identify applicable obligations','Define control objectives and scope','Map owners, systems and evidence'],['Implement preventive and detective controls','Test control design and operation','Resolve overlaps and gaps'],['Publish the control register','Record exceptions','Review on regulatory change'])},
  {slug:'evidence-management',title:'Evidence Management',summary:'Collect, protect and retain audit evidence consistently.',objective:'Provide reliable evidence without excessive manual effort.',sections:sections(['Define evidence types and retention','Set access and integrity requirements','Automate collection where practical'],['Validate completeness and timestamps','Remove sensitive excess data','Test retrieval for audits'],['Maintain evidence ownership','Record chain of custody','Review retention schedules'])},
  {slug:'access-certification',title:'Access Certification',summary:'Review privileged and standard access against current responsibilities.',objective:'Remove unnecessary access and demonstrate accountable approval.',sections:sections(['Inventory identities, roles and entitlements','Identify owners and reviewers','Define high-risk access criteria'],['Run periodic reviews','Remove or remediate inappropriate access','Track unresolved decisions'],['Archive approvals and removals','Report overdue reviews','Improve role design'])},
  {slug:'policy-assurance',title:'Policy Assurance',summary:'Validate that technical policy is deployed, monitored and governed effectively.',objective:'Demonstrate consistent enforcement and controlled exception handling.',sections:sections(['Define policy intent and scope','Map enforcement mechanisms','Establish exception criteria'],['Measure compliance and drift','Remediate material deviations','Test exception expiry and review'],['Publish assurance results','Assign corrective actions','Update standards when needed'])},
  {slug:'audit-readiness',title:'Audit Readiness',summary:'Prepare systems, teams and evidence for internal or external audit.',objective:'Reduce audit disruption and improve confidence in control operation.',sections:sections(['Confirm audit scope and contacts','Review control and evidence status','Identify likely gaps early'],['Run a readiness assessment','Resolve evidence and ownership issues','Prepare concise technical explanations'],['Track audit findings','Assign remediation owners','Retain closure evidence'])},
];

export const platformOperationsGuides:EnterpriseGuide[]=[
  {slug:'platform-operating-model',title:'Platform Operating Model',summary:'Define platform ownership, product management, support and governance.',objective:'Operate the platform as a dependable internal product.',sections:sections(['Identify platform users and outcomes','Define product and technical ownership','Set decision and escalation paths'],['Run service reviews and roadmap planning','Manage demand and technical debt','Measure adoption and reliability'],['Publish responsibilities','Track outcomes and risks','Review the model as scale changes'])},
  {slug:'capacity-management',title:'Capacity Management',summary:'Forecast and manage compute, storage, network and service limits.',objective:'Maintain sufficient capacity while controlling waste and risk.',sections:sections(['Identify constrained resources and quotas','Collect demand and growth data','Define capacity thresholds'],['Forecast future requirements','Test scaling and quota processes','Remove waste and bottlenecks'],['Publish capacity reports','Record investment decisions','Review after major onboarding'])},
  {slug:'patching-lifecycle',title:'Patching Lifecycle',summary:'Govern patch assessment, testing, deployment, exceptions and verification.',objective:'Reduce vulnerability exposure without destabilising production services.',sections:sections(['Inventory platforms and support windows','Classify patch risk and urgency','Define testing and maintenance groups'],['Test and deploy in controlled waves','Monitor failures and rollback','Track exceptions and unsupported assets'],['Retain deployment evidence','Report compliance and risk','Improve the lifecycle after incidents'])},
  {slug:'configuration-governance',title:'Configuration Governance',summary:'Control baselines, drift, exceptions and configuration ownership.',objective:'Maintain secure and supportable platform configuration at scale.',sections:sections(['Define approved baselines','Map configuration sources and owners','Set drift and exception rules'],['Detect and remediate divergence','Test configuration changes','Prevent unmanaged manual changes'],['Publish compliance status','Record approved deviations','Review baseline currency'])},
  {slug:'platform-health-review',title:'Platform Health Review',summary:'Assess reliability, security, cost, capacity and supportability of shared platforms.',objective:'Create a prioritised improvement plan based on evidence.',sections:sections(['Collect health indicators and incidents','Review lifecycle and supplier risks','Assess user experience and demand'],['Identify systemic weaknesses','Prioritise corrective investment','Track improvements and outcomes'],['Publish the health report','Assign owners and dates','Review quarterly'])},
];
