import type { EnterpriseGuide } from './enterprise-center-data';

const sections=(discover:string[],execute:string[],assure:string[])=>[
  {heading:'Discover and define',items:discover},
  {heading:'Execute and improve',items:execute},
  {heading:'Assure and evidence',items:assure},
];

export const learningPathGuides:EnterpriseGuide[]=[
  {slug:'foundation-path',title:'Foundation Learning Path',summary:'Build essential concepts, terminology and hands-on confidence in a controlled sequence.',objective:'Create a realistic foundation plan with clear milestones and evidence.',sections:sections(['Assess current knowledge and role expectations','Select prerequisite concepts and tools','Define weekly milestones and study time'],['Complete focused lessons and guided labs','Practise commands and troubleshooting','Review progress at each milestone'],['Record completed evidence','Close identified knowledge gaps','Agree the next learning stage'])},
  {slug:'practitioner-path',title:'Practitioner Learning Path',summary:'Move from guided exercises to repeatable delivery and operational ownership.',objective:'Develop practical implementation capability supported by portfolio evidence.',sections:sections(['Choose role-aligned capabilities','Map labs, projects and operational scenarios','Define success measures'],['Deliver reusable implementations','Troubleshoot realistic failures','Document decisions and trade-offs'],['Complete a practical assessment','Publish portfolio evidence','Identify readiness gaps'])},
  {slug:'architect-path',title:'Architect Learning Path',summary:'Develop requirements analysis, option assessment and architecture governance skills.',objective:'Demonstrate architecture reasoning across security, resilience, cost and operations.',sections:sections(['Define architecture competency areas','Select case studies and design exercises','Map stakeholder and governance expectations'],['Produce target designs and alternatives','Defend decisions under challenge','Run resilience and risk reviews'],['Publish architecture records','Complete peer review','Create an improvement plan'])},
  {slug:'specialist-path',title:'Specialist Learning Path',summary:'Build deep expertise in a focused technology or operating discipline.',objective:'Reach demonstrable specialist depth while maintaining enterprise context.',sections:sections(['Select a specialist domain and boundaries','Identify advanced topics and failure modes','Define expert-level evidence'],['Run complex labs and investigations','Create reusable standards and guidance','Mentor through review scenarios'],['Validate depth through assessment','Publish specialist artefacts','Maintain a currency plan'])},
  {slug:'leadership-path',title:'Technical Leadership Path',summary:'Develop delivery leadership, influence, risk ownership and executive communication.',objective:'Show measurable technical leadership beyond individual implementation.',sections:sections(['Identify leadership situations and stakeholders','Define decision rights and escalation paths','Select measurable team outcomes'],['Lead design and delivery reviews','Resolve conflict and ambiguity','Communicate risk and progress clearly'],['Capture outcomes and lessons','Request stakeholder feedback','Maintain a leadership evidence log'])},
];

export const skillMatrixGuides:EnterpriseGuide[]=[
  {slug:'capability-baseline',title:'Capability Baseline',summary:'Establish current proficiency using observable evidence rather than self-rating alone.',objective:'Create a credible baseline for development planning.',sections:sections(['Define capability categories','Set proficiency descriptions','Collect recent delivery evidence'],['Review evidence with a peer','Separate knowledge from practical ability','Record confidence and exposure'],['Approve the baseline','Identify priority gaps','Schedule reassessment'])},
  {slug:'role-readiness-matrix',title:'Role Readiness Matrix',summary:'Map technical and behavioural capabilities to a target role.',objective:'Determine whether a learner can perform the role safely and independently.',sections:sections(['Define target responsibilities','Map mandatory and desirable skills','Set evidence thresholds'],['Assess practical scenarios','Review communication and judgement','Identify supervised experience needs'],['Record readiness decisions','Create a gap-closure plan','Set the next review date'])},
  {slug:'team-coverage-matrix',title:'Team Coverage Matrix',summary:'Visualise primary, secondary and missing capability coverage across a team.',objective:'Reduce key-person risk and improve support resilience.',sections:sections(['List services and critical capabilities','Identify primary and backup owners','Define minimum coverage'],['Validate real operational experience','Plan cross-training and shadowing','Track leave and on-call exposure'],['Report material gaps','Assign mitigation owners','Review quarterly'])},
  {slug:'evidence-rubric',title:'Evidence Rubric',summary:'Standardise how labs, projects, incidents and designs demonstrate proficiency.',objective:'Make skill assessments consistent and auditable.',sections:sections(['Define acceptable evidence types','Set quality and recency rules','Describe proficiency indicators'],['Score sample evidence','Calibrate reviewers','Resolve ambiguous cases'],['Publish the rubric','Record assessment rationale','Review for bias and relevance'])},
  {slug:'development-plan',title:'Capability Development Plan',summary:'Turn assessed gaps into sequenced learning and delivery actions.',objective:'Create a measurable plan linked to role and business outcomes.',sections:sections(['Prioritise material gaps','Select learning and experience actions','Set realistic dates'],['Complete training and supervised delivery','Collect evidence continuously','Adjust based on feedback'],['Measure improvement','Close completed actions','Define the next development cycle'])},
];

export const releaseReadinessGuides:EnterpriseGuide[]=[
  {slug:'design-readiness',title:'Design Readiness Review',summary:'Confirm architecture, ownership and controls are mature enough to enter delivery.',objective:'Prevent unresolved design risk from moving into implementation.',sections:sections(['Confirm scope and requirements','Review architecture and dependencies','Identify open decisions'],['Validate security, resilience and cost','Confirm ownership and delivery approach','Resolve critical assumptions'],['Record approval conditions','Assign residual risks','Archive review evidence'])},
  {slug:'deployment-readiness',title:'Deployment Readiness Review',summary:'Validate release artefacts, environments, approvals and rollback before change execution.',objective:'Ensure deployment can proceed safely and predictably.',sections:sections(['Confirm release scope and versions','Verify environments and access','Review change and communication plans'],['Test deployment and rollback','Validate monitoring and support coverage','Confirm dependency readiness'],['Record go or no-go decision','Capture exceptions','Retain release evidence'])},
  {slug:'production-readiness',title:'Production Readiness Review',summary:'Assess operability, security, support and resilience before live service acceptance.',objective:'Release only services that are supportable and controlled.',sections:sections(['Review service ownership and support model','Confirm monitoring, backup and recovery','Validate security and compliance'],['Exercise failure and restoration','Review capacity and cost controls','Complete operational handover'],['Obtain acceptance','Record known risks','Schedule post-release validation'])},
  {slug:'change-readiness',title:'Change Readiness Review',summary:'Confirm people, process, communication and technical controls for a material change.',objective:'Reduce implementation and adoption risk.',sections:sections(['Identify impacted users and services','Assess technical and organisational change','Define communication and training'],['Validate implementation steps','Confirm support and escalation','Run readiness checkpoints'],['Approve the change window','Track adoption issues','Complete benefits review'])},
  {slug:'release-closure',title:'Release Closure Review',summary:'Verify outcomes, evidence, incidents and follow-up actions after deployment.',objective:'Close releases with accountable learning and complete records.',sections:sections(['Confirm deployed scope and status','Collect validation and incident data','Review outstanding defects'],['Complete documentation and handover','Assign corrective actions','Communicate final status'],['Archive evidence','Measure outcomes','Feed lessons into standards'])},
];

export const serviceCatalogueGuides:EnterpriseGuide[]=[
  {slug:'service-definition',title:'Service Definition',summary:'Describe purpose, users, boundaries, dependencies and ownership for a technical service.',objective:'Create an unambiguous catalogue entry that supports consumers and operators.',sections:sections(['Define customer outcomes and scope','Identify owners and support teams','Map dependencies and exclusions'],['Document features and service options','Define access and request processes','Publish support and escalation paths'],['Review with stakeholders','Set review dates','Maintain version history'])},
  {slug:'service-level-model',title:'Service-Level Model',summary:'Define availability, support, recovery and performance commitments.',objective:'Align service expectations with measurable operational capability.',sections:sections(['Identify critical user journeys','Set service indicators and objectives','Define support hours and priorities'],['Validate monitoring and reporting','Test recovery commitments','Agree error-budget or exception handling'],['Publish commitments','Track performance','Review breaches and trends'])},
  {slug:'request-model',title:'Service Request Model',summary:'Standardise how users request access, provisioning, changes and support.',objective:'Provide efficient self-service while retaining appropriate governance.',sections:sections(['List common request types','Define required information and approvals','Set fulfilment targets'],['Create workflows and automation','Test exception and rejection paths','Integrate status communication'],['Measure fulfilment performance','Remove avoidable friction','Review request demand'])},
  {slug:'support-model',title:'Service Support Model',summary:'Define support tiers, responsibilities, escalation and supplier engagement.',objective:'Ensure incidents and requests reach accountable teams quickly.',sections:sections(['Map support teams and hours','Define severity and escalation rules','Document supplier dependencies'],['Test contact and handoff paths','Validate on-call and access readiness','Create support runbooks'],['Publish the model','Measure handoff quality','Review after major incidents'])},
  {slug:'service-lifecycle',title:'Service Lifecycle',summary:'Manage introduction, operation, improvement and retirement of catalogue services.',objective:'Keep services current, supported and aligned to organisational needs.',sections:sections(['Define lifecycle states and entry criteria','Assign product and technical ownership','Set health and investment measures'],['Run regular service reviews','Prioritise improvement and technical debt','Plan retirement and migration'],['Record lifecycle decisions','Communicate material changes','Archive retired-service evidence'])},
];
