import type { EnterpriseGuide } from './enterprise-center-data';

const guide=(slug:string,title:string,summary:string,objective:string,sections:EnterpriseGuide['sections']):EnterpriseGuide=>({slug,title,summary,objective,sections});

export const projectGuides:EnterpriseGuide[]=[
 guide('foundation-project','Foundation Project','Build a small but complete implementation with clear scope, evidence and review criteria.','Prove core capability through a bounded end-to-end project.',[{heading:'Project delivery',items:['Define the problem, users and success criteria','Create a minimal architecture and delivery plan','Implement the solution with version control','Validate functionality, security and operability','Present evidence, limitations and next improvements']}]),
 guide('production-project','Production-Ready Project','Extend a working solution with resilience, governance, monitoring and operational readiness.','Demonstrate production engineering rather than feature completion alone.',[{heading:'Production expectations',items:['Document service levels and failure modes','Add security, policy and access controls','Implement monitoring, alerting and diagnostics','Prepare deployment, rollback and recovery procedures','Complete a production-readiness review']}]),
 guide('migration-project','Migration Project','Plan and execute a controlled migration from a legacy or manual approach.','Show discovery, sequencing, risk control and measurable transition outcomes.',[{heading:'Migration stages',items:['Inventory the current state and dependencies','Define target architecture and acceptance criteria','Plan waves, coexistence and rollback','Execute validation and cutover activities','Close risks and document lessons learned']}]),
 guide('automation-project','Automation Project','Replace a repeatable manual process with governed automation.','Create safe automation with inputs, approvals, evidence and failure handling.',[{heading:'Automation lifecycle',items:['Baseline the manual process and pain points','Define interfaces, validations and permissions','Build idempotent automation','Add testing, logging and recovery behaviour','Measure time, quality and risk improvement']}]),
 guide('capstone-project','Enterprise Capstone','Combine architecture, delivery, operations and leadership into one assessed outcome.','Produce a portfolio-grade artefact that demonstrates senior capability.',[{heading:'Capstone evidence',items:['Capture business and technical requirements','Defend architecture decisions and trade-offs','Deliver through controlled engineering practices','Demonstrate operational and financial awareness','Present outcomes to technical and non-technical reviewers']}]),
];

export const portfolioGuides:EnterpriseGuide[]=[
 guide('case-study','Technical Case Study','Convert completed work into a concise problem-action-outcome narrative.','Create credible evidence for interviews, promotion and professional review.',[{heading:'Case-study structure',items:['Describe context without exposing sensitive data','State constraints, risks and personal responsibility','Explain decisions and alternatives considered','Quantify technical and business outcomes','Record lessons and what you would improve']}]),
 guide('architecture-portfolio','Architecture Portfolio','Present designs with assumptions, diagrams, decisions and validation evidence.','Show how architecture responds to real constraints.',[{heading:'Portfolio evidence',items:['Include context and quality attributes','Use readable diagrams with clear boundaries','Record key architecture decisions','Explain security, resilience and cost trade-offs','Add review feedback and final changes']}]),
 guide('delivery-evidence','Delivery Evidence Pack','Demonstrate controlled implementation through commits, pipelines, tests and releases.','Make delivery capability easy to inspect and verify.',[{heading:'Evidence pack',items:['Link requirements to implementation','Show repository and branching discipline','Include automated quality evidence','Record deployment and rollback results','Summarise release outcomes and defects']}]),
 guide('operations-evidence','Operations Evidence Pack','Show monitoring, incident response, maintenance and continual improvement capability.','Prove that delivered services can be operated responsibly.',[{heading:'Operational proof',items:['Define service indicators and alerts','Include a runbook and escalation path','Show a troubleshooting timeline','Record capacity, patching and recovery controls','Capture post-incident improvements']}]),
 guide('portfolio-review','Portfolio Review Checklist','Review clarity, credibility, confidentiality and technical depth before publication.','Ensure every portfolio item is defensible and professionally presented.',[{heading:'Review criteria',items:['Remove confidential identifiers and secrets','Check claims against available evidence','Improve diagrams and written structure','Separate personal contribution from team outcomes','Prepare concise interview talking points']}]),
];

export const troubleshootingGuides:EnterpriseGuide[]=[
 guide('first-five-minutes','First Five Minutes','Stabilise the situation and collect high-value evidence before changing anything.','Build a repeatable initial-triage discipline.',[{heading:'Initial triage',items:['Confirm scope, severity and recent changes','Check health, dependencies and user impact','Preserve logs, metrics and timestamps','Apply only safe containment actions','Create a working incident timeline']}]),
 guide('connectivity-failure','Connectivity Failure','Diagnose name resolution, routing, filtering, endpoints and application reachability.','Separate network symptoms from service and identity causes.',[{heading:'Diagnostic sequence',items:['Test DNS resolution and endpoint selection','Trace routes and network boundaries','Check security rules, firewalls and proxies','Validate listeners, ports and certificates','Compare working and failing paths']}]),
 guide('deployment-failure','Deployment Failure','Investigate failed builds, releases, configuration changes and partial rollouts.','Restore service while protecting evidence and limiting blast radius.',[{heading:'Recovery path',items:['Identify the exact failed stage','Compare artifact, configuration and environment','Review permissions, dependencies and quotas','Choose fix-forward or rollback deliberately','Verify recovery and prevent recurrence']}]),
 guide('performance-failure','Performance Degradation','Use latency, saturation, errors and dependency data to find the constraint.','Avoid guesswork during performance incidents.',[{heading:'Performance analysis',items:['Confirm baseline and time of degradation','Inspect compute, memory, storage and network saturation','Trace slow dependencies and external calls','Check scaling, limits and throttling','Validate the improvement with comparable measurements']}]),
 guide('identity-failure','Identity and Access Failure','Diagnose authentication, authorization, token, role and policy issues safely.','Restore legitimate access without weakening controls.',[{heading:'Identity checks',items:['Confirm identity and authentication method','Inspect token validity, claims and audience','Validate role assignments and scope','Review policy, conditional access and deny controls','Use time-bound remediation and audit evidence']}]),
];

export const checklistGuides:EnterpriseGuide[]=[
 guide('design-review','Design Review Checklist','Review requirements, boundaries, risks and quality attributes before implementation.','Catch structural problems early.',[{heading:'Review points',items:['Requirements and assumptions are explicit','Dependencies and ownership are understood','Security and resilience are designed','Cost and operability are considered','Decisions and exceptions are recorded']}]),
 guide('pre-deployment','Pre-Deployment Checklist','Confirm readiness before releasing a change.','Reduce avoidable deployment risk.',[{heading:'Release gates',items:['Artifact and configuration are approved','Testing evidence is complete','Access and environment readiness are confirmed','Rollback and communication plans exist','Monitoring and support coverage are ready']}]),
 guide('production-readiness','Production Readiness Checklist','Assess whether a service can be supported safely after launch.','Create a clear launch decision with accountable exceptions.',[{heading:'Readiness criteria',items:['Service ownership and support model exist','Monitoring, alerts and dashboards are active','Backup, recovery and continuity are tested','Security and compliance controls are verified','Known risks have owners and deadlines']}]),
 guide('incident-review','Incident Review Checklist','Run a blameless and evidence-based incident review.','Turn incidents into measurable system improvements.',[{heading:'Review agenda',items:['Timeline and impact are accurate','Contributing conditions are identified','Detection and response gaps are discussed','Actions address system causes','Owners and verification dates are assigned']}]),
 guide('handover','Technical Handover Checklist','Transfer knowledge, access, evidence and operational responsibility.','Avoid fragile ownership transitions.',[{heading:'Handover content',items:['Architecture and dependency documentation is current','Runbooks and escalation paths are tested','Access ownership and secrets are transferred safely','Open risks and technical debt are visible','Receiving team confirms operational acceptance']}]),
];