import type { EnterpriseGuide } from './enterprise-center-data';

const guide=(slug:string,title:string,summary:string,objective:string,sections:EnterpriseGuide['sections']):EnterpriseGuide=>({slug,title,summary,objective,sections});

export const labGuides:EnterpriseGuide[]=[
  guide('guided-lab','Guided Foundation Lab','Build core capability through a controlled, evidence-led exercise.','Complete a repeatable hands-on task and explain every decision.',[{heading:'Lab flow',items:['Define the target outcome and prerequisites','Build the smallest working implementation','Capture commands, screenshots and validation evidence','Record issues, fixes and lessons learned']}]),
  guide('integration-lab','Integration Lab','Connect multiple services and verify end-to-end behaviour.','Prove integration, identity, networking and operational readiness.',[{heading:'Integration checks',items:['Map dependencies and trust boundaries','Configure secure service-to-service access','Test expected and failure paths','Document observability and support requirements']}]),
  guide('failure-lab','Failure Injection Lab','Introduce controlled faults and practise diagnosis and recovery.','Improve troubleshooting discipline without risking production.',[{heading:'Failure exercise',items:['Define a safe failure hypothesis','Inject one controlled fault','Collect evidence before changing anything','Recover, validate and write the post-incident note']}]),
  guide('security-lab','Security Hardening Lab','Apply least privilege, secure defaults and verification controls.','Turn security principles into demonstrable technical evidence.',[{heading:'Hardening tasks',items:['Identify attack surface and privileged paths','Remove unnecessary access and defaults','Enable logging, alerts and protective controls','Validate with negative and positive tests']}]),
  guide('capstone-lab','Capstone Lab','Deliver a production-style solution from design through handover.','Combine architecture, delivery, operations and governance skills.',[{heading:'Capstone evidence',items:['Write requirements, assumptions and acceptance criteria','Implement through reviewed automation','Complete production-readiness validation','Present design decisions, risks and handover evidence']}]),
];

export const scenarioGuides:EnterpriseGuide[]=[
  guide('outage-scenario','Critical Outage Scenario','Respond to a high-impact service interruption under time pressure.','Demonstrate calm triage, communication and safe recovery.',[{heading:'Scenario prompts',items:['Establish impact, scope and recent change history','Stabilise service before deep diagnosis','Coordinate owners and stakeholder updates','Validate recovery and define follow-up actions']}]),
  guide('migration-scenario','Enterprise Migration Scenario','Plan and execute a complex migration with controlled risk.','Show sequencing, dependency management and rollback thinking.',[{heading:'Migration decisions',items:['Discover dependencies and non-functional requirements','Choose migration waves and entry criteria','Define rehearsal, rollback and data validation','Plan hypercare and operational transition']}]),
  guide('security-scenario','Security Incident Scenario','Contain and investigate suspected compromise while preserving evidence.','Balance rapid containment with disciplined incident response.',[{heading:'Response sequence',items:['Confirm indicators and business impact','Contain access and affected components','Preserve logs, timelines and decision records','Recover securely and close control gaps']}]),
  guide('scale-scenario','Rapid Growth Scenario','Scale a platform facing unexpected demand and cost pressure.','Make defensible capacity, resilience and FinOps decisions.',[{heading:'Scale review',items:['Measure current bottlenecks and saturation signals','Separate immediate mitigation from structural change','Model cost, performance and reliability trade-offs','Validate scaling behaviour and guardrails']}]),
  guide('governance-scenario','Governance Exception Scenario','Handle a delivery request that conflicts with platform standards.','Protect control objectives while enabling justified business outcomes.',[{heading:'Exception process',items:['Clarify the requirement and policy conflict','Assess risk and compensating controls','Define expiry, ownership and review evidence','Capture the decision and reusable learning']}]),
];

export const commandGuides:EnterpriseGuide[]=[
  guide('essential-commands','Essential Commands','Use the minimum command set needed for daily engineering work.','Build accurate muscle memory without blind copy-and-paste.',[{heading:'Command discipline',items:['Confirm context, subscription, cluster or workspace','Use read-only inspection before modification','Capture command output as evidence','Validate state after every change']}]),
  guide('diagnostic-commands','Diagnostic Commands','Collect high-value evidence during incidents and failures.','Reduce guesswork through ordered, non-destructive inspection.',[{heading:'Diagnostic order',items:['Check identity, target and current state','Inspect events, logs, health and dependencies','Compare expected and actual configuration','Record timestamps and correlation identifiers']}]),
  guide('deployment-commands','Deployment Commands','Run controlled build, plan, apply and rollout operations.','Make deployment activity repeatable and auditable.',[{heading:'Deployment controls',items:['Validate syntax and dependencies first','Preview the change and blast radius','Execute through the approved identity and path','Verify health, version and rollback readiness']}]),
  guide('recovery-commands','Recovery Commands','Perform rollback, restart, restore and failover safely.','Use recovery actions only after impact and state are understood.',[{heading:'Recovery safeguards',items:['Confirm backup, replica or previous version health','Select the least disruptive recovery action','Monitor convergence and side effects','Document final state and remaining risk']}]),
  guide('automation-snippets','Automation Snippets','Create reusable command sequences with validation and error handling.','Replace fragile manual repetition with safe automation.',[{heading:'Snippet quality',items:['Use explicit inputs and safe defaults','Fail fast with clear error messages','Keep secrets out of logs and source','Make reruns idempotent where possible']}]),
];

export const glossaryGuides:EnterpriseGuide[]=[
  guide('core-terms','Core Terms','Understand the foundational language used across the discipline.','Explain essential concepts clearly and accurately.',[{heading:'Learning method',items:['Define each term in plain language','Connect it to a real implementation example','Contrast it with commonly confused terms','Explain one operational consequence']}]),
  guide('architecture-terms','Architecture Terms','Build a vocabulary for design reviews and technical decisions.','Use architecture language precisely rather than decoratively.',[{heading:'Architecture vocabulary',items:['Describe purpose, boundary and trade-off','Relate patterns to quality attributes','Identify assumptions and constraints','Use diagrams to reinforce meaning']}]),
  guide('operations-terms','Operations Terms','Understand reliability, incident and service-management language.','Improve communication during support and production work.',[{heading:'Operational vocabulary',items:['Link terms to measurable service behaviour','Distinguish symptoms, causes and impact','Connect recovery terms to actual procedures','Use consistent language in incident records']}]),
  guide('security-terms','Security Terms','Clarify identity, trust, threat and control terminology.','Apply security language consistently in designs and reviews.',[{heading:'Security vocabulary',items:['Separate authentication, authorization and accountability','Describe threat, vulnerability, risk and control','Explain least privilege and trust boundaries','Connect terms to verification evidence']}]),
  guide('delivery-terms','Delivery Terms','Understand CI/CD, release, quality and flow terminology.','Communicate delivery risk and progress without ambiguity.',[{heading:'Delivery vocabulary',items:['Distinguish build, release and deployment','Explain artifact, environment and promotion','Connect quality gates to evidence','Relate flow metrics to delivery outcomes']}]),
];
